version: '3.8'

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/myapp
    stdin_open: true
    tty: true
    container_name: myapp_php
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    container_name: myapp_postgres

volumes:
  db_data:
